services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: generate_soal
      POSTGRES_USER: generate_soal
      POSTGRES_PASSWORD: generate_soal
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d:ro

volumes:
  postgres_data:
